// The crates on the site: six genres, fifty records each. Not the shop's stock, just what each crate feels like.
// One line per record: [artist, title]. Covers come from Apple's catalogue by artist + title, so spell them the
// way the release is listed there. Add, remove or reorder freely; the first record is the one on top of the crate.
var CRATES = [
{g:"Soul", r:[
["Marvin Gaye","What's Going On"],["Curtis Mayfield","Superfly"],["Bill Withers","Still Bill"],["Al Green","Call Me"],
["Aretha Franklin","Lady Soul"],["Otis Redding","Otis Blue"],["Stevie Wonder","Innervisions"],["Stevie Wonder","Songs in the Key of Life"],
["Donny Hathaway","Everything Is Everything"],["Roberta Flack","First Take"],["Sam Cooke","Night Beat"],["Isaac Hayes","Hot Buttered Soul"],
["Isaac Hayes","Shaft"],["Marvin Gaye","Let's Get It On"],["Marvin Gaye","I Want You"],["Al Green","Let's Stay Together"],
["Al Green","I'm Still in Love with You"],["Aretha Franklin","I Never Loved a Man the Way I Love You"],["Aretha Franklin","Amazing Grace"],["Bill Withers","Just As I Am"],
["Curtis Mayfield","Curtis"],["Curtis Mayfield","Roots"],["The Impressions","This Is My Country"],["Nina Simone","I Put a Spell on You"],
["Etta James","At Last!"],["Solomon Burke","Rock 'n Soul"],["Wilson Pickett","The Exciting Wilson Pickett"],["Sam & Dave","Hold On, I'm Comin'"],
["The Temptations","Cloud Nine"],["The Temptations","Sky's the Limit"],["Smokey Robinson & The Miracles","Going to a Go-Go"],["Gladys Knight & The Pips","Imagination"],
["The Delfonics","La-La Means I Love You"],["The Stylistics","The Stylistics"],["Harold Melvin & The Blue Notes","Black & Blue"],["The O'Jays","Back Stabbers"],
["Teddy Pendergrass","Teddy Pendergrass"],["Minnie Riperton","Perfect Angel"],["Shuggie Otis","Inspiration Information"],["Terry Callier","What Color Is Love"],
["Ann Peebles","I Can't Stand the Rain"],["Syl Johnson","Is It Because I'm Black"],["Bobby Womack","Across 110th Street"],["Bobby Womack","The Poet"],
["Leon Ware","Musical Massage"],["Willie Hutch","The Mack"],["Marvin Gaye","Here, My Dear"],["Donny Hathaway","Live"],
["Sade","Diamond Life"],["D'Angelo","Voodoo"]]},

{g:"Funk", r:[
["James Brown","Sex Machine"],["Parliament","Mothership Connection"],["The Meters","Rejuvenation"],["Sly & The Family Stone","There's a Riot Goin' On"],
["Betty Davis","They Say I'm Different"],["Cymande","Cymande"],["James Brown","The Payback"],["James Brown","In the Jungle Groove"],
["Funkadelic","Maggot Brain"],["Funkadelic","One Nation Under a Groove"],["The Meters","Look-Ka Py Py"],["The Meters","Cabbage Alley"],
["Sly & The Family Stone","Stand!"],["Sly & The Family Stone","Fresh"],["Betty Davis","Betty Davis"],["Cymande","Second Time Round"],
["Kool & The Gang","Wild and Peaceful"],["Kool & The Gang","Light of Worlds"],["Ohio Players","Honey"],["Ohio Players","Fire"],
["Earth, Wind & Fire","That's the Way of the World"],["Earth, Wind & Fire","All 'N All"],["Tower of Power","Back to Oakland"],["War","The World Is a Ghetto"],
["War","Why Can't We Be Friends?"],["Bootsy's Rubber Band","Stretchin' Out in Bootsy's Rubber Band"],["Parliament","Funkentelechy vs. the Placebo Syndrome"],["The Isley Brothers","3 + 3"],
["The Isley Brothers","The Heat Is On"],["Chic","C'est Chic"],["Chic","Risqué"],["Rufus & Chaka Khan","Rufusized"],
["Chaka Khan","Chaka"],["The Brothers Johnson","Look Out for #1"],["Prince","Dirty Mind"],["Prince","1999"],
["Zapp","Zapp"],["Cameo","Word Up!"],["Rick James","Street Songs"],["The Gap Band","Gap Band IV"],
["Fela Kuti","Zombie"],["Fela Kuti","Expensive Shit"],["Fatback Band","Yum Yum"],["The Blackbyrds","Flying Start"],
["Mandrill","Composite Truth"],["Average White Band","AWB"],["Brass Construction","Brass Construction"],["Slave","Slave"],
["Roy Ayers Ubiquity","Everybody Loves the Sunshine"],["Fred Wesley & The J.B.'s","Damn Right I Am Somebody"]]},

{g:"Jazz", r:[
["John Coltrane","A Love Supreme"],["Miles Davis","Kind of Blue"],["Alice Coltrane","Journey in Satchidananda"],["Herbie Hancock","Head Hunters"],
["Lee Morgan","The Sidewinder"],["Pharoah Sanders","Karma"],["Miles Davis","Bitches Brew"],["Miles Davis","In a Silent Way"],
["Miles Davis","Sketches of Spain"],["John Coltrane","Giant Steps"],["John Coltrane","Blue Train"],["John Coltrane","My Favorite Things"],
["Charles Mingus","Mingus Ah Um"],["Charles Mingus","The Black Saint and the Sinner Lady"],["Thelonious Monk","Brilliant Corners"],["Thelonious Monk","Monk's Dream"],
["Dave Brubeck","Time Out"],["Cannonball Adderley","Somethin' Else"],["Bill Evans","Sunday at the Village Vanguard"],["Bill Evans","Waltz for Debby"],
["Art Blakey & The Jazz Messengers","Moanin'"],["Horace Silver","Song for My Father"],["Wayne Shorter","Speak No Evil"],["Wayne Shorter","Juju"],
["Herbie Hancock","Maiden Voyage"],["Herbie Hancock","Empyrean Isles"],["Eric Dolphy","Out to Lunch!"],["Ornette Coleman","The Shape of Jazz to Come"],
["Sonny Rollins","Saxophone Colossus"],["Sonny Rollins","The Bridge"],["Grant Green","Idle Moments"],["Dexter Gordon","Go"],
["Hank Mobley","Soul Station"],["Nina Simone","Pastel Blues"],["Ahmad Jamal","At the Pershing: But Not for Me"],["Oscar Peterson","Night Train"],
["Duke Ellington","Money Jungle"],["Chet Baker","Chet Baker Sings"],["Stan Getz & João Gilberto","Getz/Gilberto"],["Sun Ra","Space Is the Place"],
["Yusef Lateef","Eastern Sounds"],["Donald Byrd","Black Byrd"],["Roy Ayers Ubiquity","He's Coming"],["Lonnie Liston Smith","Expansions"],
["Gil Scott-Heron & Brian Jackson","Winter in America"],["Weather Report","Heavy Weather"],["Return to Forever","Light as a Feather"],["Keith Jarrett","The Köln Concert"],
["Bobbi Humphrey","Blacks and Blues"],["Freddie Hubbard","Red Clay"]]},

{g:"Hip-hop", r:[
["Nas","Illmatic"],["A Tribe Called Quest","The Low End Theory"],["Madvillain","Madvillainy"],["J Dilla","Donuts"],
["De La Soul","3 Feet High and Rising"],["IAM","L'École du micro d'argent"],["Wu-Tang Clan","Enter the Wu-Tang (36 Chambers)"],["The Notorious B.I.G.","Ready to Die"],
["Dr. Dre","The Chronic"],["Public Enemy","It Takes a Nation of Millions to Hold Us Back"],["Eric B. & Rakim","Paid in Full"],["Gang Starr","Moment of Truth"],
["Pete Rock & C.L. Smooth","Mecca and the Soul Brother"],["Mobb Deep","The Infamous"],["Raekwon","Only Built 4 Cuban Linx..."],["GZA","Liquid Swords"],
["OutKast","Aquemini"],["OutKast","ATLiens"],["The Roots","Things Fall Apart"],["Lauryn Hill","The Miseducation of Lauryn Hill"],
["Mos Def","Black on Both Sides"],["Common","Like Water for Chocolate"],["Black Star","Mos Def & Talib Kweli Are Black Star"],["The Pharcyde","Bizarre Ride II the Pharcyde"],
["Digable Planets","Reachin' (A New Refutation of Time and Space)"],["Souls of Mischief","93 'til Infinity"],["Slum Village","Fantastic, Vol. 2"],["MF DOOM","Mm..Food"],
["DJ Shadow","Endtroducing....."],["Jay-Z","Reasonable Doubt"],["Jay-Z","The Blueprint"],["Kanye West","The College Dropout"],
["Kendrick Lamar","good kid, m.A.A.d city"],["Kendrick Lamar","To Pimp a Butterfly"],["Missy Elliott","Supa Dupa Fly"],["Beastie Boys","Paul's Boutique"],
["Run-DMC","Raising Hell"],["N.W.A","Straight Outta Compton"],["Ice Cube","AmeriKKKa's Most Wanted"],["Snoop Dogg","Doggystyle"],
["2Pac","All Eyez on Me"],["Cypress Hill","Cypress Hill"],["A Tribe Called Quest","Midnight Marauders"],["Ghostface Killah","Supreme Clientele"],
["Big L","Lifestylez ov da Poor & Dangerous"],["Black Moon","Enta da Stage"],["Suprême NTM","Suprême NTM"],["MC Solaar","Qui sème le vent récolte le tempo"],
["Oxmo Puccino","Opéra Puccino"],["Lunatic","Mauvais œil"]]},

{g:"Reggae", r:[
["Bob Marley & The Wailers","Exodus"],["Augustus Pablo","King Tubbys Meets Rockers Uptown"],["Burning Spear","Marcus Garvey"],["Lee Perry & The Upsetters","Super Ape"],
["Toots & The Maytals","Funky Kingston"],["Horace Andy","Skylarking"],["Bob Marley & The Wailers","Catch a Fire"],["Bob Marley & The Wailers","Natty Dread"],
["Bob Marley & The Wailers","Kaya"],["Peter Tosh","Legalize It"],["Bunny Wailer","Blackheart Man"],["The Congos","Heart of the Congos"],
["Culture","Two Sevens Clash"],["The Abyssinians","Satta Massagana"],["Max Romeo & The Upsetters","War ina Babylon"],["Junior Murvin","Police and Thieves"],
["The Heptones","Night Food"],["The Mighty Diamonds","Right Time"],["Israel Vibration","The Same Song"],["Black Uhuru","Red"],
["Gregory Isaacs","Night Nurse"],["Dennis Brown","Visions of Dennis Brown"],["Jimmy Cliff","The Harder They Come"],["Desmond Dekker","Israelites"],
["The Skatalites","Ska Authentic"],["The Upsetters","Blackboard Jungle Dub"],["King Tubby","Dub from the Roots"],["Scientist","Scientist Rids the World of the Evil Curse of the Vampires"],
["Prince Far I","Under Heavy Manners"],["Big Youth","Screaming Target"],["U-Roy","Version Galore"],["I-Roy","Presenting I Roy"],
["Linton Kwesi Johnson","Forces of Victory"],["Steel Pulse","Handsworth Revolution"],["Alton Ellis","Sunday Coming"],["Ken Boothe","Everything I Own"],
["John Holt","1000 Volts of Holt"],["Marcia Griffiths","Naturally"],["Sister Nancy","One Two"],["Barrington Levy","Bounty Hunter"],
["Yellowman","Mister Yellowman"],["Eek-A-Mouse","Wa-Do-Dem"],["Sugar Minott","Black Roots"],["Johnny Clarke","Rockers Time Now"],
["Hugh Mundell","Africa Must Be Free by 1983"],["Yabby You","Conquering Lion"],["Keith Hudson","Pick a Dub"],["Jackie Mittoo","Keep On Dancing"],
["Toots & The Maytals","In the Dark"],["Third World","96° in the Shade"]]},

{g:"Brazil", r:[
["Jorge Ben","Samba Esquema Novo"],["Elis Regina & Tom Jobim","Elis & Tom"],["Caetano Veloso","Transa"],["Os Mutantes","Os Mutantes"],
["Milton Nascimento & Lô Borges","Clube da Esquina"],["Arthur Verocai","Arthur Verocai"],["Jorge Ben","A Tábua de Esmeralda"],["Jorge Ben","África Brasil"],
["Gilberto Gil","Refazenda"],["Gilberto Gil","Gilberto Gil"],["Caetano Veloso","Caetano Veloso"],["Various Artists","Tropicália ou Panis et Circencis"],
["Gal Costa","Gal Costa"],["Gal Costa","Índia"],["Tim Maia","Racional, Vol. 1"],["Tim Maia","Tim Maia"],
["Marcos Valle","Previsão do Tempo"],["Marcos Valle","Garra"],["Azymuth","Light as a Feather"],["Azymuth","Águia Não Come Mosca"],
["João Gilberto","Chega de Saudade"],["João Gilberto","João Gilberto"],["Antônio Carlos Jobim","Wave"],["Antônio Carlos Jobim","Stone Flower"],
["Elis Regina","Elis"],["Elis Regina","Falso Brilhante"],["Chico Buarque","Construção"],["Novos Baianos","Acabou Chorare"],
["Secos & Molhados","Secos & Molhados"],["Milton Nascimento","Milagre dos Peixes"],["Milton Nascimento","Minas"],["Lô Borges","Lô Borges"],
["Nara Leão","Dez Anos Depois"],["Baden Powell & Vinicius de Moraes","Os Afro-Sambas"],["Sérgio Mendes & Brasil '66","Herb Alpert Presents Sergio Mendes & Brasil '66"],["Astrud Gilberto","The Astrud Gilberto Album"],
["Hermeto Pascoal","Slaves Mass"],["Egberto Gismonti","Sol do Meio Dia"],["Dom Um Romão","Dom Um Romão"],["Airto Moreira","Fingers"],
["Flora Purim","Butterfly Dreams"],["Banda Black Rio","Maria Fumaça"],["Cassiano","Cuban Soul"],["Di Melo","Di Melo"],
["Hyldon","Na Rua, na Chuva, na Fazenda"],["Erasmo Carlos","Carlos, Erasmo"],["Rita Lee","Fruto Proibido"],["Raul Seixas","Krig-Ha, Bandolo!"],
["Joyce","Feminina"],["Tom Zé","Estudando o Samba"]]}
];
